greenbone/eulabeia

.github/workflows/hygiene.yml
.github/workflows/unittest.yml
README.md
cmd/eulabia-director/main.go
cmd/eulabia-sensor/main.go
go.mod
go.sum
hello.go
hello_test.go
libdirector/messagehandler.go
libdirector/messagehandler_test.go
messages/messages.go
models/target.go

Adds a pipeline for detecting common mistakes and running unit tests.
Creates a dummy for eulabia-director and eulabia-sensor.
Creates an initial MessageHandler to showcase separation of library and
cmds.
**What**:
**Why**:
**How**:
**Checklist**:

Add pipeline, initial go.mod

---

.github/CODEOWNERS
CHANGELOG.md

**What**:
**Why**:
**How**:
**Checklist**:

Add codeowners and Changelog

---

CHANGELOG.md
cmd/eulabeia-director/main.go
cmd/eulabeia-sensor/main.go
cmd/example-client/main.go
director/scan/scan.go
director/scan/scan_test.go
director/sensor/sensor.go
director/sensor/sensor_test.go
director/target/target.go
director/target/target_test.go
docs/architecture/messaging.md
internal/test/verifier.go
messages/cmds/cmds.go
messages/handler/handler.go
messages/handler/handler_test.go
messages/info/info.go
messages/messages.go
models/scan.go
models/target.go
sensor/memory/memory.go
sensor/memory/memory_test.go

**What**:
In preparation of Topic normalization this commit separate info                                                                                                of messages into a own module.                                                                                                                                  
In preparation of Topic normalization this commit separate cmds of                                                                                              
messages into a own module. 
Due to the normalization of the topic structure there is no need to                                                                                             manually create a SendResponse struct but rather let the handler decide …

Topic redesign

---

CHANGELOG.md
cmd/eulabeia-director/main.go
cmd/eulabeia-sensor/main.go
cmd/example-client/main.go
process/block.go
process/doc.go

- Simplify block until SIGTERM

Create method for block until SIGTERM

---

messages/cmds/cmds.go
messages/info/info.go

This refactors the duplicate type definitions for the same struct

Deduplicate message definitions

---

cmd/eulabeia-director/main.go
cmd/eulabeia-sensor/main.go
cmd/example-client/main.go
config/config_handler.go
config/config_handler_test.go
config/environment.go

- config_handler should return err instead of panic
- Add possibility to override configuration file via environment variables

configuration handling

---

.github/workflows/smoke.yml
CHANGELOG.md
Makefile
README.md
cmd/example-client/main.go
director/scan/scan.go

- Use cmd/example-client as smoke test
To run the smoke tests execute:
```
make smoke-tests
```

use example as smoke tests

---

CHANGELOG.md
director/target/target_test.go
docs/architecture/messaging.md
messages/cmds/cmds.go
messages/handler/on_message.go
models/target.go

**What**:
changed type of credentials in target struct: `map[string]string -> map[string]map[string]string`
**Why**:
Now we are able to specify what the credentials are used for (ssh, smb, esxi, snmp)
**How**:
**Checklist**:

adapt credentials in director

---

docs/architecture/README.md

**What**:
**Why**:
**How**:
**Checklist**:

Link message and topic structure

---

.github/workflows/docker.yml

**What**:
Fix build context for build-helper
**Why**:
**How**:
**Checklist**:

Fix wrong build context . for build-helper to .docker

---

CHANGELOG.md
models/vts.go

**What**:
**Why**:
**How**:
**Checklist**:

Add model for VTs

---

CHANGELOG.md
models/result.go

**What**:
Add GotResult and result structure.
**Why**:
**How**:
**Checklist**:

Add model for results

---

docs/messaging.md

Use context instead of group for a more general term.
**What**:
**Why**:
**How**:
**Checklist**:

Update messaging docs

---

cmd/example-client/main.go

The smoke test should wait until the scan is initialized before
succeeding.

Change example client to wait for init instead of queued

---

CHANGELOG.md
cmd/eulabeia-sensor/main.go
sensor/handler/handler.go
sensor/handler/handler_test.go
sensor/scanner/openvas/openvas.go
sensor/scanner/openvas/openvas_test.go
sensor/sensor.go
sensor/sensor_test.go
util/queueList.go
util/queueList_test.go

**What**:
Splitting up the scheduler into smaller parts. Removing allot of Channels and replaced it with Mutex. Sensor does work more event based now as the scheduler only handles the Queue for new scans. All other functionalities like changing scan status and loading VTs is now separated in own functions.
Added all missing Tests for the sensor.
Added handling for interrupted scans when scan process terminates unexpectedly.
**Why**:
The code is easier to read and testing the sensor module is possible now.
**How**:
**Checklist**:

Refactor sensor, Complete tests for sensor

---

models/result.go

**What**:
Adjust the result message struct to the current agreed draft.
**Why**:
Just keep the current message format in sync. It is still a draft.
**How**:
**Checklist**:

Update result message model to current draft

---

CHANGELOG.md
cmd/example-client/main.go
director/scan/scan_preprocessor_test.go
director/target/target.go
messages/handler/on_message.go
models/target.go
models/vts.go

**What**:
Implementing VT struct for target and adjust parsing. 
**Why**:
**How**:
**Checklist**:

Implement vt struct for target

---

CHANGELOG.md
sensor/sensor.go

**What**:
**Why**:
**How**:
**Checklist**:

Fix finished scans

---

c/example/start_scan.c
c/libeulabeia/include/eulabeia/client.h
c/libeulabeia/include/eulabeia/json.h
c/libeulabeia/include/eulabeia/types.h
c/libeulabeia/src/eulabeia_client.c
c/libeulabeia/src/eulabeia_json.c
cmd/example-client/main.go

Add possibility to transform EulabeiaStatus to json string.

Add: various json handling for openvas

---

.docker/build-helper.Dockerfile
broker.Dockerfile
eulabeia-c-library.Dockerfile
sensor.Dockerfile

**What**:
**Why**:
**How**:
**Checklist**:

Change: switch eulabeia-c-library to debian:stable

---

cmd/example-client/main.go

**What**:
Since the openvas scanner now runs through the status for wait for should be finished instead of interrupted.
**Why**:
**How**:
**Checklist**:

Change: set smoke test to wait for finished instead of interrupted

---

cmd/example-client/main.go
sensor/handler/handler.go

**What**:
Example client waits until a sensor is registered within the director.
**Why**:
This eliminates the strict order and race conditions of the client, director and sensor. The smoke-test should now work again.
**How**:
**Checklist**:

Fix smoke test

---

CHANGELOG.md
cmd/eulabeia-director/main.go
cmd/eulabeia-sensor/main.go
cmd/example-client/main.go
config.toml
config/config.go
director/vt/vt.go
director/vt/vt_test.go
feedservice/feedservice.go
feedservice/handler/handler.go
models/result.go
models/target.go

**What**:
Support get VT within director and adjust smoke-test
SC-283
**Why**:
In order for a client to use the get vt functionality the director has to resolve the scan ID to the corresponding sensor.
**How**:
Automatically:
Run the smoke-test
Manually:
Start director sensor and example client.
**Checklist**:

Get vts director

---

storage/rsa.go

**What**:
add chunking for rsa encryption
**Why**:
This way we can encrypt and decrypt messages
which are longer than the public key size.
**How**:
**Checklist**:

Add: add chunking for rsa encryption

---

c/libeulabeia/include/eulabeia/json.h
c/libeulabeia/include/eulabeia/types.h
c/libeulabeia/src/eulabeia_json.c
cmd/example-client/main.go
director/scan/mega_scan.go
director/scan/scan_preprocessor_test.go
director/target/target.go
models/target.go

**What**:
Add test_alive_hosts_only, methods_bitflag and
ports fields.
Jira: SC-413
**Why**:
**How**:
**Checklist**:

Add: add alive test parameters

---

.github/workflows/docker.yml

**What**:
**Why**:
**How**:
**Checklist**:

Remove buildhelper from docker.yml

---

c/example/CMakeLists.txt
c/example/generate_description.c
c/example/start_mega_scan.c
c/example/start_scan.c
c/libeulabeia/test/src/got_vts_json.h
director/scan/mega_scan.go
director/vt/vt.go
director/vt/vt_test.go
feedservice/feedservice.go
feedservice/feedservice_test.go
feedservice/handler/handler.go
feedservice/redis/redis.go
logging/configuration/init.go
messages/handler/register.go
messages/handler/register_test.go
plugins/keys.nasl
plugins/plugin_feed_info.inc
plugins/test.nasl
sensor/handler.go
sensor/handler_test.go
sensor/scanner/openvas/openvas.go
sensor/scanner/openvas/openvas_test.go
sensor/scanner/scanner.go
sensor/sensor_test.go
storage/rsa.go
util/memory_test.go
util/queueList_test.go

**What**:
Update license headers.
**Why**:
**How**:
**Checklist**:

Update license header

---

client/client_test.go
client/init.go
cmd/eulabeia-sensor/main.go
cmd/example-client/main.go
director/scan/scan.go
director/sensor/sensor.go
director/target/target.go
director/vt/vt.go
feedservice/feedservice.go
feedservice/handler/handler.go
messages/info/info.go
messages/messages.go
models/result.go
models/scan.go
sensor/handler.go
sensor/handler_test.go
sensor/sensor.go

**What**:
1. create a new client module
2. change example client to use client module instead of doing it via handler
3. refactor sensor to do some things via the client module instead of using the handler setup
To make it easier to write clients for eulabeia a new client module will be introduced; with that module it should be relevatively easy to create and run standard cases (like create target, create scan and start scan) without having to somehoe integrate into the handler design.
To showcase the client module the example client is rewritten to use that.
**Why**:
**How**:
**Checklist**:

Refactor smoketest
